# Generated by Django 3.2.10 on 2021-12-19 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokesite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='evolves_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokesite.pokemon'),
        ),
    ]
