# Generated by Django 3.2.10 on 2022-01-01 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokesite', '0003_auto_20211228_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='charged_attack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='default_secondary', to='pokesite.chargedattack'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='fast_attack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='default_primary', to='pokesite.fastattack'),
        ),
        migrations.AlterField(
            model_name='trainerpokemon',
            name='charged_attack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='default', to='pokesite.chargedattack'),
        ),
        migrations.AlterField(
            model_name='trainerpokemon',
            name='second_charged_attack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='optional', to='pokesite.chargedattack'),
        ),
    ]
