# Generated by Django 3.2.10 on 2022-01-06 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokesite', '0004_auto_20220101_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='charged_attack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='default_secondary', to='pokesite.chargedattack'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='evolves_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokesite.pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='fast_attack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='default_primary', to='pokesite.fastattack'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image_shiny',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='trainerpokemon',
            name='charged_attack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='default', to='pokesite.chargedattack'),
        ),
        migrations.AlterField(
            model_name='trainerpokemon',
            name='fast_attack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pokesite.fastattack'),
        ),
        migrations.AlterField(
            model_name='trainerpokemon',
            name='second_charged_attack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='optional', to='pokesite.chargedattack'),
        ),
    ]
